[package]
name = "google-fonts-downloader"
version = "1.0.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.36", features = ["cargo"] }
reqwest = { version = "0.12.15", features = ["blocking"] }
regex = "1.10.3"

[lints.clippy]
pedantic = "deny"
